name: Deploy DIGIY DRIVER to VPS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e
            cd /var/www/digiy-driver
            sudo -u www-data git fetch --all
            sudo -u www-data git reset --hard origin/main
            sudo -u www-data git clean -fd
            echo "Deployed: $(date -u) | $(sudo -u www-data git rev-parse --short HEAD)"
